language: objective-c
osx_image: xcode10.1

script:
- set -o pipefail && xcodebuild test -workspace extensions-kit.xcworkspace -scheme extensions-kit -sdk iphonesimulator12.1 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint

- xcodebuild -scheme extensions-kit -workspace extensions-kit.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone XS,OS=12.1' build test

after_success:
- bash <(curl -s https://codecov.io/bash)
curl --data-binary @codecov.yml https://codecov.io/validate
