//
//  Dictionary+Map.swift
//  extensions-kit
//
//  Created by Astemir Eleev on 07/09/2018.
//  Copyright © 2018 Astemir Eleev. All rights reserved.
//

import Foundation

extension Dictionary {
    
    /// Filters out self with the same keys as the 'map'  input parameter, and values generated by running each [key: value] by dicscarding nil values and mapping keys with values
    public func map(_ map: (Key, Value) -> (Key, Value)?) -> [Key: Value] {
        var mapped = [Key: Value]()
        
        each {
            if let value = map($0, $1) {
                mapped[value.0] = value.1
            }
        }
        
        return mapped
    }
}
